#! /usr/bin/env python3

import os
import sys

from bs4 import BeautifulSoup
import requests
from slugify import slugify

def save_page_link(url: str):
    req = requests.get(url)
    html = BeautifulSoup(req.content, 'html.parser')
    title = html.head.title.text.strip()
    slug = slugify(title)
    fname = f'{slug}.md'

    with open(fname, 'w', encoding='utf-8') as page:
        page.write(f'''# {title}

\<<{req.url}>\>
''')

    print(f'Link salvo no arquivo: {fname}')

def main():
    if len(sys.argv) > 1:
        for url in sys.argv[1:]:
            save_page_link(url)
    else:
        while (url := input('URL: ')):
            save_page_link(url)

if __name__ == '__main__':
    main()
